stages:
  - build

build-job:
  stage: build
  image: ubuntu:18.04
  script:
    - apt update
    - apt -y upgrade
#    - apt search 5.4.0-109-generic
    - apt --yes install build-essential linux-headers-5.4.0-109-generic linux-modules-5.4.0-109-generic libxtables-dev iptables kmod
    - ln -s /lib/modules/5.4.0-109-generic /lib/modules/5.4.109+
    - mkdir -p /lib/modules/5.4.109+/kernel/net/netfilter/
    - make
    - make install
 #   - find /lib/modules/5.4.109+/
    - depmod -a
    - modprobe xt_TRAFSTAT
    - ifconfig -a
    - iptables -I INPUT -p icmp -s 127.0.0.1 -j TRAFSTAT --local-net 127.0.0.1
    - ping -c 1 127.0.0.1
    - cat /proc/trafstat/127.0.0.1_32 | grep 1,2130706433,2130706433,0,0,2,0,169,0,0 