image: ubuntu:22.04

stages:
  - build

variables:
  DEBIAN_FRONTEND: noninteractive

before_script:
  - apt update
  - apt -y install build-essential libxtables-dev iptables iputils-ping kmod
  - apt -y install linux-headers-5.15.0-1089-azure
  - apt -y install linux-headers-6.1.0-1036-oem
  - apt -y install linux-headers-6.5.0-1027-oem
  - apt -y install linux-headers-6.8.0-1030-gcp
  - apt -y install gcc-11 gcc-12

build:
  stage: build
  script:
    - make KERNEL_VERSION=5.15.0-1089-azure
    - modinfo xt_TRAFSTAT.ko
    - make clean

    - make KERNEL_VERSION=6.1.0-1036-oem
    - modinfo xt_TRAFSTAT.ko
    - make clean

    - make KERNEL_VERSION=6.5.0-1027-oem
    - modinfo xt_TRAFSTAT.ko
    - make clean

    - make KERNEL_VERSION=6.8.0-1030-gcp
    - modinfo xt_TRAFSTAT.ko
    - make clean
