stages:
  - build

build-job:
  stage: build
  image: ubuntu:18.04
  script:
    - apt update
    - apt -y upgrade
    - apt search linux-headers
    - apt --yes install build-essential linux-headers-5.4.0-109-generic
    - make
    - make install
    - iptables -I INPUT -p icmp -s 127.0.0.1 -j TRAFSTAT --local-net 127.0.0.1
    - ping -c 1 127.0.0.1
    - cat /proc/trafstat/127.0.0.1_32 | grep 1,2130706433,2130706433,0,0,2,0,169,0,0 